apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: prod
  annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000